export const MESSAGES = {
  DATABASE: {
    CONNECT_SUCCESS: '🌱 Successfully connected to the database.',
    DISCONNECT_SUCCESS: '⛔️ Successfully disconnected from the database.',
    USERNAME: 'Username credentials to access the database main',
    PASSWORD: 'Password credentials to access the database main ',
  },
  AUTH: {
    GOOGLE_EMAIL_NOT_FOUND: 'Unable to retrieve email from Google. Please try again.',
    GOOGLE_LOGIN_FAILED: 'Google login failed. Please try again.',
    GOOGLE_CALLBACK_FAILED: 'Google OAuth callback failed',
    FACEBOOK_LOGIN_FAILED: 'Facebook login failed. Please try again.',
    FACEBOOK_EMAIL_NOT_FOUND: 'Unable to retrieve email from Facebook.',
    INVALID_OAUTH_STATE: 'Invalid authentication state data.',
    FACEBOOK_TOKEN_FETCH_FAILED: 'Failed to obtain Facebook access token',
    FACEBOOK_USER_FETCH_FAILED: 'Failed to fetch Facebook user info',
    INVALID_ROLE_ID: 'The specified role ID does not exist.',
    ACCESS_TOKEN_REQUIRED: 'Access token is required',
    FACEBOOK_CONFIG_MISSING: 'Facebook OAuth configuration is missing',
    FACEBOOK_AUTH_URL_GENERATION_FAILED: 'Failed to generate Facebook auth URL',
    USER_AGENT_AND_IP_REQUIRED: 'User agent and IP are required',
    USER_NOT_FOUND: 'User not found',
    DEVICE_ID_AND_IP_REQUIRED: 'Device ID and IP address are required',
    PROFILE_UPDATED: 'Update successfully',
    OAUTH_CREATE_FAILED: 'Failed to process OAuth user registration',
    USER_CREATE_RACE_CONDITION: 'User created concurrently but not found.',
    OAUTH_CREATE_SUCCESS: 'OAuth user processed successfully',
    DEVICE_REGISTER_FAILED: 'Failed to register device',
    REFRESH_TOKEN_DELETE_FAILED: 'Failed to delete refresh tokens for device',
    OTP: {
      NAME: 'Gmail account display name for OTP.',
      ACCOUNT: 'Gmail account email for OTP.',
      PASSWORD: 'Gmail account password for OTP.',
    },
    JWT: {
      SECRET_KEY: 'Unique secret string for JWT, stored securely.',
      REFRESH_TOKEN_KEY: 'Unique refresh token secret string, stored securely.',
      EXPIRATION: {
        ACCESS_TOKEN: 'Access token expiration duration.',
        REFRESH_TOKEN: 'Refresh token expiration duration.',
      },
      ALGORITHM: 'List of allowed JWT algorithms.',
      OTP_SECRET: 'Security string for OTP.',
    },
  },
  ENVIRONMENT: {
    PORT: 'Server port.',
    HOST: 'Server host.',
    DEV: 'Environment is a collection of procedures and tools for developing, testing and debugging an application or program.',
    PROD: 'Environment contains just the final version of the product in order to avoid any confusion or security vulnerabilities',
    TEST: 'Testing environment setup.',
  },
  CLIENT: {
    REQUEST: {
      POINT: 'Maximum points consumable over duration.',
      DURATION: 'Seconds before points reset.',
      PASSWORD_SECRET: 'Security string for passwords.',
      OTP_SECRET: 'Security string for OTP.',
      COOKIE_EXPIRATION: 'Cookie expiration duration.',
      SECRET_COOKIE_NAME: 'Cookie name for successful login/register.',
      PATHS: {
        PROVINCE_JSON: 'Path to province.json file.',
        OPENAPI_YAML: 'Path to paths.yaml file.',
      },
      SERVER_URL: 'Backend URL.',
    },
  },
  ERROR_MESSAGES: {
    AUTH: {
      LOGIN: 'Login process failed',
      REGISTER: 'Registration process failed',
      LOGOUT: 'Logout process failed',
      PERMISSION: 'Insufficient permissions to access resource.',
      UPDATE: 'Failed to update user profile',
    },
    ROLE: {
      GET_ALL_ROLE: 'Failed to retrieve users role',
      GET_ROLE_USER: 'Retrieving users by role failed',
      NOT_FOUND: 'This role does not exist',
    },
    OTP: {
      FIND_OTP: 'Failed to find OTP',
      GENERATED_OTP: 'OTP generation failed',
      VERIFY_OTP: 'OTP verification failed',
      SEND_FAILURE: 'OTP sending failed',
    },
    USER: {
      GET_ALL_USER: 'Failed to retrieve users',
      CHANGE_PASSWORD: 'Password change failed',
      FORGOT_PASSWORD: 'Forgot-password process failed',
      VERIFY_FORGOT_PASSWORD_TOKEN: 'Forgot-password token verification failed',
      ACCOUNT_INACTIVE: 'Your account has not been activated.',
    },
    CV: {
      CREATE_FAILED: 'Failed to create CV. Please try again.',
      DUPLICATE: 'CV with this configuration already exists',
      INVALID_REFERENCE: 'Invalid user or template reference',
      TEMPLATE_NOT_FOUND: 'Referenced template not found',
    },
  },
  SUCCESS_MESSAGES: {
    LOGIN: 'Login successfully.',
    REGISTER: 'Registration successfully.',
    LOGOUT: 'Logout successfully.',
    CONFIRM: 'Email confirmed successfully',
    RESEND_LINK: 'Confirmed link had sent successfully',
    DATA_RETRIEVAL: 'Data retrieval successfully.',
    DATA_MANIPULATION: 'Data manipulation successfully.',
    OTP: {
      VERIFY: 'OTP verification successfully.',
      RESEND: 'OTP resend successfully.',
    },
    AUTH: {
      GET_ALL: 'Get all user successfully',
      GET_BY_ID: 'Get user profile details by admin successfully',
      UPDATE: 'Successfully update user account',
      INSERT: 'Successfully create user account',
      DELETE: 'Successfully deleted user account(s) ',
      GET_ROLES: 'All user role retrieved successfully.',
      GET_ROLE_BY_ID: 'Get user profile details by admin successfully',
      UPDATE_ROLE: 'Successfully update role user',
      DELETE_ROLE: 'Successfully deleted role user',
      RESET_PASSWORD: 'Reset password successfully.',
      LOGOUT: 'Logout successfully',
      ROLE: {
        UPDATE: 'Update user role successfully',
      },
    },
    USER: {
      REFRESH_TOKEN: 'Token refreshed successfully.',
      FORGOT_PASSWORD: 'Forgot password request processed successfully.',
      VERIFY_FORGOT_PASSWORD: 'Forgot password verified successfully.',
      RESET_PASSWORD: 'Password reset successfully.',
      CHANGE_PASSWORD: 'Password changed successfully.',
      GET_LIST_ORDER_BY_USER: 'Get list orders by user successfully!',
      GET_ALL: 'All users retrieved successfully.',
      GET_BY_ID: 'User retrieved successfully.',
      GET_PROFILE: 'Profile fetched successfully.',
      UPDATE: 'Updated successfully.',
      SEARCH: 'User search completed successfully.',
      DELETE: 'User deleted successfully.',
      DELETE_MANY_USER: 'Multiple users deleted successfully.',
      GET_ROLE: 'User roles retrieved successfully.',
      EDIT_ROLE: 'User roles edited successfully.',
      GET_FAVORITE_FRIEND: 'List of close friends retrieved successfully.',
      PAGINATION: 'User pagination executed successfully.',
      TEST_TOKEN: 'Token test completed successfully.',
      GET_PRODUCT_FAVORITE: 'Favorite products retrieved successfully.',
      UPLOAD_AVATAR: 'Avatar uploaded successfully.',
      UPLOAD_THUMBNAIL: 'Thumbnail uploaded successfully.',
      UPLOAD_IMAGE: 'Image uploaded successfully.',
      UPLOAD_MUL_IMAGE: 'Multiple images were uploaded successfully.',
      GET_BOOKING_HISTORY: 'Get booking history successfully.',
      AVATAR_UPDATED: 'Update avatar successfully',
    },
    IMAGE: {
      GET_ALL: 'Successfully retrieved all images.',
      GET_BY_ID: 'Get detail image by image_id',
      CLEAR: 'Clear all image successfully',
      DELETE: 'Successfully deleted image',
      UPLOAD_IMAGE: 'Image uploaded successfully.',
      UPLOAD_MUL_IMAGE: 'Multiple images were uploaded successfully.',
    },
  },
  VALIDATION_MESSAGES: {
    TITLE: 'Validation Errors.',
    UPLOAD: {
      IMAGE: {
        INVALID_IMAGE_EXTENSION: 'Image extension is invalid.',
        INVALID_IMAGE_SIZE: 'Image size is too large.',
        MAX_IMAGE_UPLOAD: 'A maximum of 4 images can be uploaded.',
      },
    },
    USER: {
      REQUIRED_ID: 'UserId is required',
      COMMONS: {
        NOT_LOGIN: 'You must be logged in to continue.',
        ID_IS_INVALID: 'User ID is invalid.',
        ID_MUST_BE_A_STRING: 'User ID must be a string.',
        ID_CAN_NOT_BE_EMPTY: 'User ID cannot be empty.',
        WITH_ID_IS_NOT_EXIST: 'User with the specified ID does not exist.',
        NOT_ROLE_NOT_SATISFIED: 'You do not have the appropriate role to access these resources.',
        INVALID_INCLUDES: 'Invalid pagination inclusion.',
        EMAIL_OR_PASSWORD_IS_INCORRECT: 'The email or password is incorrect.',
        INVALID_BEARER_TOKEN: 'The bearer token is invalid.',
        HEADER_AUTHORIZATION_IS_INVALID: 'Authorization header is invalid.',
        EMAIL: {
          IS_REQUIRED: 'Email is required.',
          MUST_BE_A_STRING: 'Email must be a string.',
          ACCESSIBILITY: 'The email address does not exist. Please use a valid one or register.',
          NOT_REGISTER: 'Email is not registered.',
          ALREADY_EXISTS: 'User with this email already exists',
          VALID_EMAIL: 'Email address is invalid.',
          VALID_DOMAIN: 'Email must end with @gmail.com or @gmail.edu.com.',
          CONTAIN_SPECIAL_CHARACTER: 'Email must contain at least one special character.',
        },
        NAME: {
          INVALID: 'Invalid Name format.',
          IS_REQUIRED: 'Name is required.',
          MUST_BE_A_STRING: 'Name must be a string.',
          LENGTH_MUST_BE_FROM_3_TO_15: 'Name must be between 3 and 15 characters long.',
          INCLUDES_MUL_WHITESPACE: 'Name cannot contain multiple consecutive whitespaces.',
        },
        PHONE: {
          INVALID: 'Invalid phone number.',
          MUST_BE_A_STRING: 'Phone number must be a string.',
          LENGTH_MUST_BE_10_CHARACTER: 'Phone number must be 10 or 11 digits long.',
          LENGTH_MUST_BE_STRING_NUMBER: 'Phone number must be numeric.',
          IS_REQUIRED: 'Phone number is required.',
          IS_INVALID: 'Invalid phone number. Please provide a valid Vietnamese phone number.',
        },
        PASSWORD: {
          RESET_FAILED: 'Failed to reset password.',
          CHANGE_FAILED: 'Failed to change password.',
          IS_REQUIRED: 'Password is required.',
          MUST_BE_STRONG:
            'Password must meet the strength requirements: 8-16 characters including at least 1 lowercase, 1 uppercase, 1 number, and 1 symbol.',
          LENGTH_MUST_BE_FROM_6_TO_20: 'Password length must be between 6 and 20 characters.',
          CONTAINS_EMOJI: 'Password cannot contain emojis or whitespace.',
          MUST_BE_A_STRING: 'Password must be a string.',
          NOT_SAME_OLD_PASSWORD: 'New password must not be the same as the old password.',
        },
        CONFIRM_PASSWORD: {
          IS_REQUIRED: 'Confirm_password is required.',
          MUST_BE_THE_SAME_AS_PASSWORD: 'Confirm_password must match the password.',
          MUST_BE_A_STRING: 'Confirm_password must be a string.',
          LENGTH_MUST_BE_FROM_6_TO_20: 'Confirm_password length must be between 6 and 20 characters.',
          MUST_BE_STRONG:
            'Confirm_password must meet the strength requirements 8-16 characters including at least 1 lowercase, 1 uppercase, 1 number, and 1 symbol.',
          CONTAINS_EMOJI: 'Confirm password cannot contain emojis or whitespace.',
        },
        OLD_PASSWORD: {
          IS_REQUIRED: 'Old password is required.',
          IS_INCORRECT: 'Old password is incorrect.',
        },
        FILE: {
          INVALID: 'Invalid file type or file too large',
          INVALID_EXTENSION: 'Invalid file type. Only .jpg, .jpeg, .bmp, .gif, .png are allowed.',
          INVALID_SIZE: 'Image dimensions should not exceed 1024x1024 pixels',
        },
      },
      TOKEN: {
        EMAIL_VERIFY: {
          IS_REQUIRED: 'An email verification token is required.',
          MUST_BE_A_STRING: 'The email verification token must be a string.',
        },
        ACCESS_TOKEN: {
          IS_REQUIRED: 'An access token is required.',
          MUST_BE_A_STRING: 'The access token must be a string.',
        },
        REFRESH_TOKEN: {
          IS_REQUIRED: 'Refresh token is required for logout.',
          IS_NOT_EXIST: 'The refresh token has been used or does not exist.',
          NOT_FOUND: 'Attempted to delete a non-existent refresh token.',
          MUST_BE_A_STRING: 'The refresh token must be a string.',
          IS_NOT_EXIST_IN_COOKIES: 'There is no refresh token in cookies.',
        },
      },
      ROLE: {
        IS_REQUIRED: 'Role is required',
        INVALID_USER_ROLE: 'User role must be valid.',
        USER_ROLE_CAN_NOT_BE_EMPTY: 'User role cannot be empty.',
        DUL_USER_ROLE: 'Updating to the same role is not allowed.',
        USER_EDIT_ROLE_THEMSELVES: 'Users cannot edit their own role.',
        ROLE_IS_EXISTS: 'Role name do not exist in the database',
      },
      LOGIN: {
        USER_NOT_FOUND: 'User not found',
        EMAIL_IS_REQUIRED: 'Email is required.',
        EMAIL_MUST_BE_A_STRING: 'Email must be a string.',
        EMAIL_INVALID: 'Email address is invalid',
        EMAIL_ACCESSIBILITY: 'The email address does not exist. Please use a valid one or register.',
        PASSWORD_IS_REQUIRED: 'Password is required.',
        PASSWORD_MUST_BE_A_STRING: 'Password must be a string.',
        PASSWORD_MUST_BE_STRONG:
          'Password must be 8-16 characters, including at least 1 lowercase, 1 uppercase, 1 number, and 1 symbol.',
        PASSWORD_LENGTH_MUST_BE_FROM_8_TO_16: 'Password length must be between 8 and 16 characters.',
        PASSWORD_IS_INCORRECT: 'The email or password is incorrect.',
        PASSWORD_CONTAINS_EMOJI: 'Password cannot contains emoji symbol and white space',
        ACCOUNT_IS_UNVERIFIED: 'The account is unverified.',
        ACCOUNT_IS_BANNED: 'The account is banned.',
        ACCOUNT_NOT_FOUND: 'Account not found.',
        ACCOUNT_NOT_EXISTS: 'The user’s account has been removed.',
        EMAIL_OR_PASSWORD: 'Email or password is not correct',
      },
      REGISTER: {
        INVALID_FULLNAME: 'Must be a valid full_name',
        FULL_NAME_IS_REQUIRED: 'Full name is required.',
        FULL_NAME_MUST_BE_A_STRING: 'Full name must be a string.',
        FULL_NAME_LENGTH_MUST_BE_FROM_3_TO_30: 'Full name length must be between 3 and 30 characters.',
        FULL_NAME_INCLUDES_MUL_WHITESPACE: 'Full name cannot contain multiple consecutive whitespaces.',
        EMAIL_IS_REQUIRED: 'Email is required.',
        EMAIL_MUST_BE_A_STRING: 'Email must be a valid address.',
        EMAIL_ACCESSIBILITY: 'The email address is already in use. Please use a different email.',
        PASSWORD_IS_REQUIRED: 'Password is required.',
        PASSWORD_MUST_BE_A_STRING: 'Password must be a string.',
        PASSWORD_MUST_BE_STRONG:
          'Password must meet the strength requirements: 8-16 characters including at least 1 lowercase, 1 uppercase, 1 number, and 1 symbol.',
        PASSWORD_LENGTH_MUST_BE_FROM_8_TO_16: 'Password length must be between 8 and 16 characters.',
        PASSWORD_CAN_NOT_CONTAIN_SPACE: 'Password cannot contain spaces.',
        CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required.',
        CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string.',
        CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Confirm password must match the password.',
        CONFIRM_PASSWORD_MUST_BE_STRONG:
          'Confirm password must meet the strength requirements: 8-16 characters including at least 1 lowercase, 1 uppercase, 1 number, and 1 symbol.',
        CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_16: 'Confirm password length must be between 8 and 16 characters.',
        INVALID_PHONE: 'Phone number must be valid.',
        PHONE_MUST_BE_A_STRING: 'Phone must be a string.',
        PHONE_LENGTH_MUST_BE_10_CHARACTER: 'Phone length must be 10 or 11 characters.',
        PHONE_LENGTH_MUST_BE_STRING_NUMBER: 'Phone number must be numeric.',
        PHONE_IS_REQUIRED: 'Phone is required.',
        PHONE_MUST_BE_STRING: 'Phone must be a string.',
        PHONE_IS_INVALID: 'The phone number is invalid. Please enter a valid Vietnamese phone number.',
      },
      VERIFY_OTP: {
        INVALID_OTP: 'Invalid OTP.',
        IS_REQUIRED: 'OTP is required.',
        IS_NOT_EXIST: 'OTP not found.',
        MUST_BE_A_STRING: 'OTP must be a string.',
        OPT_LENGTH_MUST_BE_6: 'OTP length must be 6 characters.',
        NOT_FOUND_OR_ALREADY_VERIFIED: 'User not found or OTP already verified.',
        IS_NUMBERIC: 'OTP must be numeric.',
        IS_EXPIRED: 'OTP has expired.',
      },
      VERIFY_FORGOT_PASSWORD_TOKEN: {
        IS_REQUIRED: 'Forgot_password token is required.',
        MUST_BE_A_STRING: 'Forgot_password token must be a string.',
        LENGTH_MUST_BE_6: 'Forgot_password token length must be 6 characters.',
        IS_NOT_EXIST: 'Forgot_password token not found.',
        IS_EXPIRED: 'Forgot_password token has expired.',
        NOT_FOUND_OR_ALREADY_VERIFIED: 'User not found or forgot_password token already verified.',
        INVALID_TOKEN: 'Invalid forgot_password token.',
        IS_NUMBERIC: 'Forgot_password token must be numeric.',
      },
      PROFILE: {
        USER_NOT_FOUND: 'User not found',
        FIELD_UPDATE_IS_REQUIRED: 'At least one field must be specified for updating.',
        INVALID_FULLNAME: 'Full_name must be valid.',
        FULLNAME_INCLUDES_MUL_WHITESPACE: 'Full name cannot contain multiple consecutive whitespaces.',
        FULL_NAME_MUST_BE_A_STRING: 'Full name must be a string.',
        FULL_NAME_MAX_LENGTH_IS_50: 'Full name length must be between 4 and 50 characters.',
        INVALID_PHONE: 'Phone number must be valid.',
        PHONE_MUST_BE_A_STRING: 'Phone must be a string.',
        PHONE_LENGTH_MUST_BE_10_CHARACTER: 'Phone length must be 10 or 11 characters.',
        PHONE_LENGTH_MUST_BE_STRING_NUMBER: 'Phone number must be numeric.',
        PHONE_IS_REQUIRED: 'Phone is required.',
        PHONE_MUST_BE_STRING: 'Phone must be a string.',
        PHONE_IS_INVALID: 'The phone number is invalid. Please enter a valid Vietnamese phone number.',
        GENDER_MUST_BE_STRING: 'Gender must be a string.',
        GENDER_IS_INVALID: 'Gender is invalid. Please specify as Male, Female, Other, etc.',
        AVATAR_MUST_BE_STRING: 'Avatar image must be a string.',
        VALID_URL_AVATAR: 'Avatar URL must be valid and have a valid image extension.',
        VALID_URL_COVER_PHOTO: 'Cover photo URL must be valid and have a valid image extension.',
        COVER_PHOTO_MUST_BE_STRING: 'Cover photo must be a string.',
        INVALID_ADDRESS: 'Address must be valid.',
        ADDRESS_MUST_BE_STRING: 'Address must be a string.',
        ADDRESS_LENGTH_IS_INVALID: 'Address length must be between 10 and 200 characters.',
        ADDRESS_INCLUDES_MUL_WHITESPACE: 'Address cannot contain multiple consecutive whitespaces.',
      },
    },
  },
  CLOUDINARY: {
    KEY: 'Key to access cloudinary',
    SECRET: 'Password to access cloudinary',
    NAME: 'Cloud name of current cloudinary account',
    AVATAR_FOLDER: 'Folder that contain avatar images on cloudinary',
    THUMBNAIL_FOLDER: 'Folder that contain thumbnail images on cloudinary',
    BANNER_FOLDER: 'Folder that contain banner images on cloudinary',
    IMAGE_FOLDER: 'Folder that contain image images on cloudinary',
  },
  ERROR_RESPONSE: {
    TOO_MANY_RES: 'Too many accounts created from this IP, please try again after a millisecond',
    INTERNAL_SERVER_RES: 'Internal server error',
  },
  API_MESSAGES: {
    AUTH: {
      LOGIN: {
        MESSAGE_TITLE: 'Login user into the system',
        MESSAGE_SUMARY: 'Authenticates a user and returns a token upon successful authentication',
      },
      REGISTER: {
        MESSAGE_TITLE: 'Register a new user',
        MESSAGE_SUMARY: 'Creates a new user account with the provided details.',
      },

      GET_ALL_USER: {
        MESSAGE_TITLE: 'Get all user by admin',
        MESSAGE_SUMARY: 'Retrieve a paginated list of users',
      },
    },
  },
  CV: {
    TITLE: {
      REQUIRED: 'CV title is required.',
      MAX_LENGTH: 'CV title must not exceed 100 characters.',
      MIN_LENGTH: 'CV title must be greater than 3 characters.',
    },
    TEMPLATE: {
      NOT_FOUND: 'Template not found.',
    },
    TEMPLATE_ID: {
      INVALID: 'Invalid template ID format.',
    },
    PERSONAL_INFO: {
      FULL_NAME: {
        REQUIRED: 'Full name is required.',
        INVALID: 'Full name contains invalid characters.',
      },
      JOB_TITLE: {
        INVALID: 'Invalid job title.',
      },
      EMAIL: {
        REQUIRED: 'Email is required.',
        INVALID: 'Invalid email address.',
      },
      PHONE: {
        INVALID: 'Invalid phone number.',
      },
      ADDRESS: {
        INVALID: 'Invalid address.',
      },
      CITY: {
        INVALID: 'Invalid city.',
      },
      STATE: {
        INVALID: 'Invalid state.',
      },
      COUNTRY: {
        INVALID: 'Invalid country.',
      },
      POSTAL_CODE: {
        INVALID: 'Invalid postal code.',
      },
      DATE_OF_BIRTH: {
        INVALID: 'Invalid date of birth format.',
      },
      NATIONALITY: {
        INVALID: 'Invalid nationality.',
      },
      MARITAL_STATUS: {
        INVALID: 'Invalid marital status value.',
      },
      DRIVING_LICENSE: {
        INVALID: 'Invalid driving license value.',
      },
      PROFILE_PICTURE: {
        INVALID: 'Invalid profile picture URL.',
      },
      WEBSITE: {
        INVALID: 'Invalid website URL.',
      },
      LINKEDIN: {
        INVALID: 'Invalid LinkedIn URL.',
      },
      GITHUB: {
        INVALID: 'Invalid GitHub URL.',
      },
      PORTFOLIO: {
        INVALID: 'Invalid portfolio URL.',
      },
      TWITTER: {
        INVALID: 'Invalid Twitter URL.',
      },
      FACEBOOK: {
        INVALID: 'Invalid Facebook URL.',
      },
      INSTAGRAM: {
        INVALID: 'Invalid Instagram URL.',
      },
      PERSONAL_SUMMARY: {
        INVALID: 'Invalid personal summary.',
      },
      CAREER_OBJECTIVE: {
        INVALID: 'Invalid career objective.',
      },
      HOBBIES: {
        INVALID: 'Invalid hobbies value.',
      },
      REFERENCES: {
        INVALID: 'Invalid references value.',
      },
      ADDITIONAL_INFO: {
        INVALID: 'Invalid additional information.',
      },
    },
  },
}
